export const mensagens = {
  app: {
    shortName: 'SGP',
    name: 'Sistema de Gerenciamento de Padarias',
    eyebrow: 'Sistema de Gerenciamento de Padarias',
  },
  common: {
    add: 'Adicionar',
    cancel: 'Cancelar',
    save: 'Salvar',
    search: 'Pesquisar',
    status: 'Status',
    date: 'Data',
    total: 'Total',
    quantity: 'Quantidade',
    revenue: 'Faturamento',
    estimatedProfit: 'Lucro estimado',
    averageTicket: 'Ticket médio',
    orders: 'Pedidos',
    units: 'Unidades',
    ingredients: 'Ingredientes',
    supplier: 'Fornecedor',
    suppliers: 'Fornecedores',
    buyer: 'Comprador',
    customers: 'Clientes',
    bread: 'Pão',
    category: 'Categoria',
    document: 'Documento',
    phone: 'Telefone',
    contactName: 'Contato',
    stock: 'Estoque',
    minimum: 'Mínimo',
    unitCost: 'Custo un.',
    noRecords: 'Nenhum registro encontrado.',
  },
  actions: {
    addRecipe: 'Adicionar receita',
    addIngredient: 'Novo ingrediente',
    addPurchase: 'Nova compra',
    addSale: 'Nova venda',
    addSupplier: 'Novo fornecedor',
    addCustomer: 'Novo cliente',
    firstResult: 'Primeiro resultado',
    goToDashboard: 'Ir para o painel',
    viewRecipes: 'Ver receitas',
    simulateProduction: 'Simular produção',
  },
  nav: {
    dashboard: 'Painel',
    breadRecipes: 'Receitas de pão',
    ingredients: 'Ingredientes',
    purchases: 'Compras',
    sales: 'Vendas',
  },
  tabs: {
    navigation: 'Navegação por abas',
    overview: 'Visão geral',
    recipes: 'Receitas',
    simulateProduction: 'Simular produção',
    breads: 'Pães',
    purchases: 'Compras',
    sales: 'Vendas',
    customers: 'Clientes',
    suppliers: 'Fornecedores',
  },
  options: {
    ingredientCategories: {
      farinha: 'Farinha',
      fermento: 'Fermento',
      tempero: 'Tempero',
      açucar: 'Açúcar',
      liquido: 'Líquidos',
      gordura: 'Gordura',
      vegetal: 'Vegetais',
      grao: 'Grãos',
      recheio: 'Recheios',
      outro: 'Outros',
    },
    paymentMethods: {
      Pix: 'Pix',
      Cartão: 'Cartão',
      Dinheiro: 'Dinheiro',
    },
    purchaseStatuses: {
      Recebida: 'Recebida',
      Pendente: 'Pendente',
    },
  },
  forms: {
    recipe: {
      title: 'Cadastrar receita',
      name: 'Nome do pão',
      salePrice: 'Preço de venda',
      yieldUnits: 'Rendimento',
      preparationTimeMinutes: 'Tempo de preparo',
      ingredientsSection: 'Ingredientes da receita',
      ingredient: 'Ingrediente',
      addIngredient: 'Adicionar ingrediente',
      removeIngredient: 'Remover ingrediente',
    },
    ingredient: {
      title: 'Cadastrar ingrediente',
      name: 'Nome do ingrediente',
      category: 'Categoria',
      unit: 'Unidade',
      costPerUnit: 'Custo por unidade',
      stockQuantity: 'Estoque atual',
      minStockQuantity: 'Estoque mínimo',
    },
    purchase: {
      title: 'Cadastrar compra',
      supplierName: 'Fornecedor',
      ingredient: 'Ingrediente',
      unitCost: 'Custo unitário',
    },
    sale: {
      title: 'Cadastrar venda',
      buyerName: 'Comprador',
      customer: 'Cliente / balcão',
      bread: 'Pão vendido',
      paymentMethod: 'Forma de pagamento',
    },
    supplier: {
      title: 'Cadastrar fornecedor',
      name: 'Nome do fornecedor',
      document: 'CNPJ/CPF',
      phone: 'Telefone',
      contactName: 'Pessoa de contato',
    },
    customer: {
      title: 'Cadastrar cliente',
      name: 'Nome do cliente',
      document: 'CNPJ/CPF',
      phone: 'Telefone',
    },
  },
  validation: {
    required: 'Campo obrigatório',
    positive: 'Informe um valor maior que zero',
    positiveInteger: 'Informe um número inteiro maior que zero',
    minOneIngredient: 'Informe ao menos um ingrediente',
  },
  pages: {
    dashboard: {
      title: 'Painel de Gerenciamento',
      period: 'Período analisado 01/01/2026 à 31/12/2026',
      totalSold: 'Total vendido',
      soldSum: 'Soma de vendas no período',
      profitInfo: 'Preço de venda - custo da receita',
      purchases: 'Compras',
      pendingPurchases: 'compra(s) pendente(s)',
      lowStock: 'Estoque baixo',
      criticalIngredients: 'ingrediente(s) crítico(s)',
    },
    welcome: {
      title: 'Bem-vindo ao SGP',
      subtitle: 'Sistema de Gerenciamento de Padarias',
      description:
        'Acompanhe receitas, vendas, compras e estoque em um só lugar. Use o painel para ver os principais indicadores e navegar pelas operações do dia a dia.',
      registeredRevenue: 'Faturamento registrado',
      totalPurchased: 'Total comprado',
      ingredientsToRestock: 'Ingredientes para repor',
    },
    recipes: {
      title: 'Pães e receitas',
      searchLabel: 'Pesquisar pão',
      searchPlaceholder: 'Nome do pão ou ingrediente',
      selectForDetails: 'Selecione para ver detalhes',
      foundSuffix: 'receita(s) encontrada(s)',
      unitsPerRecipe: 'un. por receita',
      unitsPerRecipeFull: 'unidade(s) por receita',
      salePrice: 'Preço de venda',
      recipeCost: 'Custo da receita',
      costPerUnit: 'Custo por unidade',
      preparation: 'Preparo',
      estimatedProfitPerUnit: 'Lucro estimado/un.:',
      empty: 'Nenhuma receita encontrada.',
    },
    ingredients: {
      title: 'Ingredientes',
      registered: 'Ingredientes cadastrados',
      availableItems: 'Itens disponíveis para receitas',
      lowStock: 'Estoque baixo',
      criticalLevel: 'em nível crítico',
      stockValue: 'Valor em estoque',
      stockValueInfo: 'Custo estimado dos insumos',
      stockAttention: 'Atenção ao estoque',
      stockAttentionInfo:
        'Reponha os ingredientes abaixo do mínimo para evitar impacto nas próximas produções.',
      searchLabel: 'Pesquisar ingrediente',
      searchPlaceholder: 'Nome ou categoria',
    },
    purchases: {
      title: 'Compras',
      totalPurchased: 'Total comprado',
      mockOrders: 'Pedidos no mock',
      pending: 'Compras pendentes',
      awaitingReceipt: 'aguardando recebimento',
      suppliers: 'Fornecedores',
      registeredPurchases: 'compras registradas',
      searchLabel: 'Pesquisar compra',
      searchPlaceholder: 'Fornecedor, ingrediente ou status',
    },
    sales: {
      title: 'Vendas',
      saleSum: 'Soma das vendas',
      priceMinusCost: 'Preço - custo da receita',
      registeredSales: 'vendas registradas',
      searchLabel: 'Pesquisar venda',
      searchPlaceholder: 'Comprador, pão ou pagamento',
    },
    reports: {
      title: 'Relatórios',
      placeholder: 'Os relatórios consolidados serão exibidos aqui.',
    },
  },
  dashboardTabs: {
    breads: {
      unitsSold: 'Unidades vendidas',
      profitPeriod: 'Lucro estimado no período',
      bestBread: 'Pão mais vendido',
      lowestBread: 'Pão menos vendido',
      mostProfitableBread: 'Pão mais lucrativo',
      units: 'unidades',
    },
    sales: {
      buyerSum: 'Soma por comprador',
      averagePerSale: 'Média por venda',
      bestBuyer: 'Maior comprador',
      buyerCount: 'Compradores ativos',
      preferredPayment: 'Pagamento mais usado',
      paymentDistribution: 'Distribuição por forma de pagamento',
      customerRanking: 'Ranking de compradores',
      ordersSuffix: 'pedido(s)',
    },
    purchases: {
      totalSpent: 'Total gasto',
      spendingInfo: 'Compras de ingredientes',
      pendingTotal: 'Valor pendente',
      pendingInfo: 'Aguardando recebimento',
      mainSupplier: 'Principal fornecedor',
      supplierInfo: 'Maior valor comprado',
      mostPurchasedCategory: 'Categoria mais comprada',
      categoryInfo: 'Por valor gasto',
      supplierSpending: 'Gastos por fornecedor',
      categorySpending: 'Gastos por categoria',
      latestPurchases: 'Últimas compras',
    },
    overview: {
      registeredRevenue: 'Receita registrada',
      unitsSold: 'Unidades vendidas',
      sales: 'vendas',
      payments: 'Pagamentos',
      paymentDistribution: 'Distribuição por forma de pagamento',
      latestSales: 'Últimas vendas',
      saleCount: 'venda(s)',
    },
  },
  simulation: {
    parameters: 'Parâmetros da simulação',
    breadType: 'Tipo de pão',
    batches: 'Lotes',
    title: 'Simulação de Produção',
    estimatedCost: 'Custo estimado:',
    maxPossible: 'máximo possível:',
    batchesSuffix: 'lote(s)',
    enough: 'Ingredientes suficientes',
    notEnough: 'Ingredientes insuficientes',
    stockAfterProduction: 'Saldo após produção:',
    missing: 'Faltam',
    ok: 'OK',
    missingShort: 'Falta',
  },
  table: {
    breadType: 'Tipo de pão',
    sold: 'Vendidos',
    payment: 'Pagamento',
    purchases: {
      received: 'Recebida',
      pending: 'Pendente',
    },
    stockStatus: {
      ok: 'OK',
      low: 'Baixo',
      critical: 'Crítico',
    },
  },
} as const;
