export const mensagens = {
  aplicativo: {
    nomeCurto: 'SGP',
    nome: 'Sistema de Gerenciamento de Padarias',
    slogan: 'Sistema de Gerenciamento de Padarias',
  },
  comum: {
    adicionar: 'Adicionar',
    cancelar: 'Cancelar',
    salvar: 'Salvar',
    pesquisar: 'Pesquisar',
    status: 'Status',
    data: 'Data',
    total: 'Total',
    quantidade: 'Quantidade',
    faturamento: 'Faturamento',
    lucroEstimado: 'Lucro estimado',
    ticketMedio: 'Ticket médio',
    pedidos: 'Pedidos',
    unidades: 'Unidades',
    ingredientes: 'Ingredientes',
    fornecedor: 'Fornecedor',
    fornecedores: 'Fornecedores',
    comprador: 'Comprador',
    clientes: 'Clientes',
    pao: 'Pão',
    categoria: 'Categoria',
    documento: 'Documento',
    telefone: 'Telefone',
    nomeContato: 'Contato',
    estoque: 'Estoque',
    minimo: 'Mínimo',
    custoUnitario: 'Custo un.',
    semRegistros: 'Nenhum registro encontrado.',
    unidadesMedida: 'Unidades de Medida'
  },
  acoes: {
    adicionarReceita: 'Adicionar receita',
    adicionarIngrediente: 'Novo ingrediente',
    adicionarCompra: 'Nova compra',
    adicionarVenda: 'Nova venda',
    adicionarFornecedor: 'Novo fornecedor',
    adicionarCliente: 'Novo cliente',
    primeiroResultado: 'Primeiro resultado',
    irParaPainel: 'Ir para o painel',
    verReceitas: 'Ver receitas',
    simularProducao: 'Simular produção',
  },
  navegacao: {
    painel: 'Painel',
    receitasPao: 'Receitas',
    ingredientes: 'Ingredientes',
    compras: 'Compras',
    vendas: 'Vendas',
    categorias: 'Categorias',
  },
  abas: {
    navegacao: 'Navegação por abas',
    visaoGeral: 'Visão geral',
    receitas: 'Receitas',
    simularProducao: 'Simular produção',
    paes: 'Pães',
    compras: 'Compras',
    vendas: 'Vendas',
    clientes: 'Clientes',
    fornecedores: 'Fornecedores',
  },
  opcoes: {
    categoriasIngrediente: {
      farinha: 'Farinha',
      fermento: 'Fermento',
      tempero: 'Tempero',
      açucar: 'Açúcar',
      liquido: 'Líquidos',
      gordura: 'Gordura',
      vegetal: 'Vegetais',
      grao: 'Grãos',
      recheio: 'Recheios',
      outro: 'Outros',
    },
    metodosPagamento: {
      Pix: 'Pix',
      Cartão: 'Cartão',
      Dinheiro: 'Dinheiro',
    },
    statusCompra: {
      Recebida: 'Recebida',
      Pendente: 'Pendente',
    },
  },
  formularios: {
    receita: {
      titulo: 'Cadastrar receita',
      nome: 'Nome do pão',
      precoVenda: 'Preço de venda',
      rendimento: 'Rendimento',
      tempoPreparo: 'Tempo de preparo',
      secaoIngredientes: 'Ingredientes da receita',
      ingrediente: 'Ingrediente',
      adicionarIngrediente: 'Adicionar ingrediente',
      removerIngrediente: 'Remover ingrediente',
    },
    ingrediente: {
      titulo: 'Cadastrar ingrediente',
      nome: 'Nome do ingrediente',
      categoria: 'Categoria',
      unidade: 'Unidade',
      custoPorUnidade: 'Custo por unidade',
      estoqueAtual: 'Estoque atual',
      estoqueMinimo: 'Estoque mínimo',
    },
    compra: {
      titulo: 'Cadastrar compra',
      fornecedor: 'Fornecedor',
      ingrediente: 'Ingrediente',
      custoUnitario: 'Custo unitário',
    },
    venda: {
      titulo: 'Cadastrar venda',
      comprador: 'Comprador',
      cliente: 'Cliente / balcão',
      pao: 'Pão vendido',
      formaPagamento: 'Forma de pagamento',
    },
    fornecedor: {
      titulo: 'Cadastrar fornecedor',
      nome: 'Nome do fornecedor',
      documento: 'CNPJ/CPF',
      telefone: 'Telefone',
      nomeContato: 'Pessoa de contato',
    },
    cliente: {
      titulo: 'Cadastrar cliente',
      nome: 'Nome do cliente',
      documento: 'CNPJ/CPF',
      telefone: 'Telefone',
    },
  },
  validacao: {
    obrigatorio: 'Campo obrigatório',
    positivo: 'Informe um valor maior que zero',
    inteiroPositivo: 'Informe um número inteiro maior que zero',
    minimoUmIngrediente: 'Informe ao menos um ingrediente',
  },
  paginas: {
    painel: {
      titulo: 'Painel de Gerenciamento',
      periodo: 'Período analisado 01/01/2026 à 31/12/2026',
      totalVendido: 'Total vendido',
      somaVendas: 'Soma de vendas no período',
      infoLucro: 'Preço de venda - custo da receita',
      compras: 'Compras',
      comprasPendentes: 'compra(s) pendente(s)',
      estoqueBaixo: 'Estoque baixo',
      ingredientesCriticos: 'ingrediente(s) crítico(s)',
    },
    boasVindas: {
      titulo: 'Bem-vindo ao SGP',
      subtitulo: 'Sistema de Gerenciamento de Padarias',
      descricao:
        'Acompanhe receitas, vendas, compras e estoque em um só lugar. Use o painel para ver os principais indicadores e navegar pelas operações do dia a dia.',
      faturamentoRegistrado: 'Faturamento registrado',
      totalComprado: 'Total comprado',
      ingredientesParaRepor: 'Ingredientes para repor',
    },
    receitas: {
      titulo: 'Pães e receitas',
      pesquisar: 'Pesquisar pão',
      placeholderPesquisa: 'Nome do pão ou ingrediente',
      selecioneParaDetalhes: 'Selecione para ver detalhes',
      sufixoEncontradas: 'receita(s) encontrada(s)',
      unidadesPorReceita: 'un. por receita',
      unidadesPorReceitaCompleto: 'unidade(s) por receita',
      precoVenda: 'Preço de venda',
      custoReceita: 'Custo da receita',
      custoPorUnidade: 'Custo por unidade',
      preparo: 'Preparo',
      lucroEstimadoPorUnidade: 'Lucro estimado/un.:',
      vazio: 'Nenhuma receita encontrada.',
    },
    ingredientes: {
      titulo: 'Ingredientes',
      cadastrados: 'Ingredientes cadastrados',
      itensDisponiveis: 'Itens disponíveis para receitas',
      estoqueBaixo: 'Estoque baixo',
      nivelCritico: 'em nível crítico',
      valorEstoque: 'Valor em estoque',
      infoValorEstoque: 'Custo estimado dos insumos',
      atencaoEstoque: 'Atenção ao estoque',
      infoAtencaoEstoque:
        'Reponha os ingredientes abaixo do mínimo para evitar impacto nas próximas produções.',
      pesquisar: 'Pesquisar ingrediente',
      placeholderPesquisa: 'Nome ou categoria',
    },
    compras: {
      titulo: 'Compras',
      totalComprado: 'Total comprado',
      pedidosMock: 'Pedidos no mock',
      pendentes: 'Compras pendentes',
      aguardandoRecebimento: 'aguardando recebimento',
      fornecedores: 'Fornecedores',
      comprasRegistradas: 'compras registradas',
      pesquisar: 'Pesquisar compra',
      placeholderPesquisa: 'Fornecedor, ingrediente ou status',
    },
    vendas: {
      titulo: 'Vendas',
      somaVendas: 'Soma das vendas',
      precoMenosCusto: 'Preço - custo da receita',
      vendasRegistradas: 'vendas registradas',
      pesquisar: 'Pesquisar venda',
      placeholderPesquisa: 'Comprador, pão ou pagamento',
    },
    relatorios: {
      titulo: 'Relatórios',
      placeholder: 'Os relatórios consolidados serão exibidos aqui.',
    },
  },
  abasPainel: {
    paes: {
      unidadesVendidas: 'Unidades vendidas',
      lucroPeriodo: 'Lucro estimado no período',
      melhorPao: 'Pão mais vendido',
      piorPao: 'Pão menos vendido',
      paoMaisLucrativo: 'Pão mais lucrativo',
      unidades: 'unidades',
    },
    vendas: {
      somaComprador: 'Soma por comprador',
      mediaPorVenda: 'Média por venda',
      melhorComprador: 'Maior comprador',
      compradoresAtivos: 'Compradores ativos',
      pagamentoPreferido: 'Pagamento mais usado',
      distribuicaoPagamento: 'Distribuição por forma de pagamento',
      rankingClientes: 'Ranking de compradores',
      sufixoPedidos: 'pedido(s)',
    },
    compras: {
      totalGasto: 'Total gasto',
      infoGastos: 'Compras de ingredientes',
      totalPendente: 'Valor pendente',
      infoPendente: 'Aguardando recebimento',
      fornecedorPrincipal: 'Principal fornecedor',
      infoFornecedor: 'Maior valor comprado',
      categoriaMaisComprada: 'Categoria mais comprada',
      infoCategoria: 'Por valor gasto',
      gastosPorFornecedor: 'Gastos por fornecedor',
      gastosPorCategoria: 'Gastos por categoria',
      ultimasCompras: 'Últimas compras',
    },
    visaoGeral: {
      faturamentoRegistrado: 'Receita registrada',
      unidadesVendidas: 'Unidades vendidas',
      vendas: 'vendas',
      pagamentos: 'Pagamentos',
      distribuicaoPagamento: 'Distribuição por forma de pagamento',
      ultimasVendas: 'Últimas vendas',
      contagemVendas: 'venda(s)',
    },
  },
  simulacao: {
    parametros: 'Parâmetros da simulação',
    tipoPao: 'Tipo de pão',
    lotes: 'Lotes',
    titulo: 'Simulação de Produção',
    custoEstimado: 'Custo estimado:',
    maximoPossivel: 'máximo possível:',
    sufixoLotes: 'lote(s)',
    suficientes: 'Ingredientes suficientes',
    insuficientes: 'Ingredientes insuficientes',
    estoqueAposProducao: 'Saldo após produção:',
    faltam: 'Faltam',
    ok: 'OK',
    falta: 'Falta',
  },
  tabela: {
    tipoPao: 'Tipo de pão',
    vendidos: 'Vendidos',
    pagamento: 'Pagamento',
    compras: {
      recebida: 'Recebida',
      pendente: 'Pendente',
    },
    statusEstoque: {
      ok: 'OK',
      baixo: 'Baixo',
      critico: 'Crítico',
    },
  },
} as const;
